### ISSUE TITLE
wget build_jshon fails

### ISSUE THREAD

**Issue by brettdellandre** [trmb-vast/vast-api-scripts#1]
Step 3: Install the supporting utilities. (wget, bc, netcat, jshon)

wget https://raw.githubusercontent.com/trmb-vast/api-tools/master/build_jshon 404s

`vastdata@vastdata:~$ wget https://raw.githubusercontent.com/trmb-vast/api-tools/master/build_jshon
--2022-06-14 00:10:31--  https://raw.githubusercontent.com/trmb-vast/api-tools/master/build_jshon
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-06-14 00:10:31 ERROR 404: Not Found.`

**Comment by brettdellandre** [comment]
resolved by: `wget https://raw.githubusercontent.com/trmb-vast/vast-api-scripts/main/build_jshon`

**Comment by brettdellandre** [comment]
@trmb-vast boop

**Comment by trmb-vast** [comment]
finally getting around to fixing this.. thanks @brettdellandre !
