### ISSUE TITLE
Updated pre-req's

### ISSUE THREAD

**Issue by brettdellandre** [trmb-vast/vast-api-scripts#2]
Ubuntu 20.04 needs `apt-get install build-essentials`
Centos/RHEL needs `yum groupinstall "Development Tools`

`# bash ./build_jshon` Fails:
`...checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/home/vastdata/jansson-2.13':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
--2022-06-14 00:13:58--  http://kmkeen.com/jshon/jshon.tar.gz
Resolving kmkeen.com (kmkeen.com)... 67.23.13.172
Connecting to kmkeen.com (kmkeen.com)|67.23.13.172|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10004 (9.8K) [application/x-gzip]
Saving to: ‘jshon.tar.gz’

jshon.tar.gz                      100%[============================================================>]   9.77K  --.-KB/s    in 0.05s

2022-06-14 00:13:59 (208 KB/s) - ‘jshon.tar.gz’ saved [10004/10004]

cp: cannot stat '../libjansson.a': No such file or directory
./build_jshon: line 18: make: command not found
./build_jshon: line 20: strip: command not found
cp: cannot stat 'jshon': No such file or directory
Note.. we also need python3 to post-process json`

`# bash ./build_jshon` Moves forward after `apt-get install build-essentials`:
`make[2]: Leaving directory '/home/vastdata/jansson-2.13'
make[1]: Leaving directory '/home/vastdata/jansson-2.13'
--2022-06-14 00:18:08--  http://kmkeen.com/jshon/jshon.tar.gz
Resolving kmkeen.com (kmkeen.com)... 67.23.13.172
Connecting to kmkeen.com (kmkeen.com)|67.23.13.172|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10004 (9.8K) [application/x-gzip]
Saving to: ‘jshon.tar.gz.1’

jshon.tar.gz.1                    100%[============================================================>]   9.77K  --.-KB/s    in 0.05s

2022-06-14 00:18:08 (208 KB/s) - ‘jshon.tar.gz.1’ saved [10004/10004]

cc -std=c99 -O3 -Wall -pedantic -Wextra -Werror    -c -o jshon.o jshon.c
cc   jshon.o  libjansson.a -o jshon
Note.. we also need python3 to post-process json`

**Comment by trmb-vast** [comment]
Finally getting around to fixing this.. thanks!
